epochs: 50
use_val: True
val_ratio: 0.25
iter_val_start: 1
iter_val_every: 1
save_best: True
save_best_all: True
multilabel: False
patience: -1
seed: 1234
lr: 0.001
weight_decay: 0.0
lr_scheduler: False
monitor: mse
recache: False
optimizer: Adam
num_layers: 2
activation: relu
multirun: 3
feat_norm: False
synth: False
scale: 1
show_last: False
gnn_encoder: FFNGIN
graph_encoder: deepset
multi_contrast: False
gnn_filters: [64, 64, 32, 16]
dropout: 0.0
deepsets: True
use_bn: False
deepsets_inner_act: relu
deepsets_outer_act: relu
fuse_type: cat
pooling: add
reduction: 2
inner_mlp: True
inner_mlp_layers: 1
outer_mlp_layers: 1
use_mlp_score: True
mlp_score_layer: 2
batch_size: 64
val_batch_size: 512
use_all_val: True
val_size: 60000
use_sim: True
NTN_layers: 4
tensor_neurons: 16
output_comb: True
use_ssl: False
use_compre: False
use_pripre: False
norm: True
use_deepsets: True
use_ff: True
num_ff: 1
sep: True
measure: JSD
cl_loss_norm: True
norm_type: tanh
clip_grad: False
num_works: 10
board_log: False
reconstruction: False
sim_rat: True
noise: True
cat_disloss: False
cat_NTN: False
com_att: False
alpha_weight: 0.0
beta_weight: 0.0
mu_weight: 0.0
lambda_weight: 1.0
rho_weight: 1.0
schedule_start: -1
detach: False
ngsa: True
neurons: False
model_name: CPRGsim
dataset_name: IMDBMulti
