dataset: "AIDS700nef"

model_name: "GSC_GNN"

GSC_GNN:
  epochs: 200
  use_val: True
  val_ratio: 0.25
  iter_val_start: 50
  iter_val_every: 1
  save_best: True
  save_best_all: True
  multilabel: False
  patience: -1
  seed: 1234
  lr: 0.001
  weight_decay: 0.0
  lr_scheduler: False
  monitor: 'mse'
  recache: False
  optimizer: 'Adam'
  num_layers: 2
  activation: 'relu'
  multirun: 2
  feat_norm: False
  synth: False
  scale: 1
  gnn_encoder: 'FFNGIN'
  graph_encoder: 'deepset'
  multi_contrast: False
  gnn_filters: [64, 64, 64, 64]
  dropout: 0.0
  deepsets: True
  use_bn: False
  deepsets_inner_act: 'relu'
  deepsets_outer_act: 'relu'
  fuse_type: 'cat'
  pooling: 'add'
  reduction: 2
  inner_mlp: True
  inner_mlp_layers: 1
  outer_mlp_layers: 1
  use_mlp_score: True
  mlp_score_layer: 2
  batch_size: 128
  val_batch_size: 512
  use_sim: True
  NTN_layers: 4
  tensor_neurons: 16
  output_comb: True
  use_ssl: True
  use_compre: False
  use_pripre: False
  use_deepsets: False
  use_ff: False
  measure: 'JSD'
  model_name: 'GSC_GNN'
  dataset_name: 'AIDS700nef'
  sep: False
  board_log: True
  reconstruction: False
  sim_rat: True
  noise: True
  cat_disloss: False
  cat_NTN: True
  com_att: False
  alpha_weight: 0.04
  beta_weight: 0.000
  mu_weight: 0.00001
  lambda_weight: 1.0
  rho_weight: 1.0
  schedule_start: -1
  detach: False

SimGNN:
  patience: -1
  seed: 1234
  monitor: "mse"
  recache: False
  multirun: 1
  feat_norm: False
  synth: False
  optimizer: "Adam"
  gnn_operator: 'gcn'
  diffpool: False
  filters_1: 64
  filters_2: 32
  filters_3: 16
  tensor_neurons: 16
  bottle_neck_neurons: 16
  bottle_neck_neurons_2: 8
  bins: 16
  batch_size: 128
  epochs: 360
  dropout: 0
  lr: 0.001
  weight_decay: 0
  histogram: True
  num_NTN_mlp: 1
